### ISSUE TITLE
[FEATURE] format and input authors for the publication tab

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/geo_to_hca#11]
As a data wrangler I would like to have the converter put the authors into the publication and contributors tab as it is fairly time consuming and error prone to do it manually.

The author information may be harvested programmatically from an API if not totally within GEO, happy to help figure out how.

**Comment by ESapenaVentura** [comment]
It does that some times, but there are errors some other times and our approach given the strict timeframe has been "Avoid the error and just don't write anything"

This should be solved in the future (Not a good approach to just ignore), so happy to keep the ticket here!

**Comment by ami-day** [comment]
Yea it does fetch the author names already given an SRA study id using the enter fetch. If you are getting empty values it is because as Enrique said, when it is not available we just add "". It might be worth considering if the author information can be retrieved from ENA in a secondary "if not" function

**Comment by ami-day** [comment]
*entrez

**Comment by mshadbolt** [comment]
I noticed there is a trailing double pipe when the script does fill the authors:
e.g.

`Treutlein B||Brownfield DG||Wu AR||Neff NF||Mantalas GL||Espinoza FH||Desai TJ||Krasnow MA||Quake SR||`

**Comment by mshadbolt** [comment]
And for authors that have a middle initial, 2 commas are inputted
e.g.
`Tushar J,,Desai  Doug G,,Brownfield`

**Comment by ami-day** [comment]
yea, that last issue is a difficult one; it's kind of hard to know if in the author info they have a middle initial or not due to the way it is formatted. So, it is added imperfectly (rather than not at all)

**Comment by ami-day** [comment]
> I noticed there is a trailing double pipe when the script does fill the authors:
> e.g.
> 
> `Treutlein B||Brownfield DG||Wu AR||Neff NF||Mantalas GL||Espinoza FH||Desai TJ||Krasnow MA||Quake SR||`

this will be easy to change, will do that when I start addressing the repo issues/tickets again (or you can if you like if you pull the repo and push the changes)

**Comment by ami-day** [comment]
Working on this issue in a new branch "issue_11"

**Comment by ami-day** [comment]
Done plus other relevant updates so I am closing this branch
