### ISSUE TITLE
[FEATURE] Add INSDC project and study accessions to Project tab

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/geo_to_hca#13]
As a data wrangler I'd like to see the project and study accessions added to the project tab automatically. I believe these should be fairly easy to retrieve programmatically.

Have to bear in mind that the project and study are switched currently in our metadata until the latest dev branch is merged to master.

**Comment by ami-day** [comment]
project.insdc_project_accessions
project.insdc_study_accessions

**Comment by ami-day** [comment]
Done so closing this ticket.
