### ISSUE TITLE
[FEATURE] Add functionality to create one combined spreadsheet rather than separate ones

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/geo_to_hca#19]
Currently when you specify a list of accessions you get given a spreadsheet per accession rather than one combined spreadsheet, I think it would be nice if it gave you one to avoid copy/pasting information into one.

**Comment by ami-day** [comment]
Closing this as the need to combine accessions into 1 spreadsheet is rare and merging them can be done easily by manual means. The optional argument to provide a list of accessions is intended where the user wants to get metadata for multiple separate projects which are considered distinct.
