### ISSUE TITLE
Fix issue with spreadsheet names not showing correctly

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/geo_to_hca#2]
**Description of the issue**:
When dealing with Superseries/more than 1 accession in a line, there is an unexpected behaviour due to returning the Superseries ID without the `GSE` prefix that results in the spreadsheets being called only by the ID without the preffix. 

**Impact/Effort estimation**
Low/Low

**Comment by ami-day** [comment]
@ESapenaVentura I don't quite understand what you mean in this description. Do you have the superseries accession which I can use to test it? Is the problem only the actual file name of the spreadsheet which is generated, or something else also?

**Comment by ESapenaVentura** [comment]
Maybe it was already fixed. There was a time we were making a lot of code changes at the same time and some reverted back because of merging.

If you haven't noticed the tool giving weird names to the spreadsheets we can close this then

**Comment by ESapenaVentura** [comment]
I have been using the tool and this is fixed. 

Closing the ticket.
