### ISSUE TITLE
Ensure all modules are in the template spreadsheet

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/geo_to_hca#20]
When converting a recent dataset I realised that 'plate-based sequencing' module is not in the template, this ticket is to systematically check which modules are missing to ensure we don't miss any metadata.

**Comment by mshadbolt** [comment]
Just noticed that dissociation and enrichment protocols are also not in the template spreadsheet even though these are commonly required

**Comment by ami-day** [comment]
Done.
