### ISSUE TITLE
issue installing sra requirements with pip and pip3

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/geo_to_hca#21]
Hi :-)
I'm having some issues with the following command:

`pip3 install -r requirements.txt --upgrade
`
I'm getting this error:

```
ERROR: Could not find a version that satisfies the requirement sra-tools (from -r requirements.txt (line 6)) (from versions: none)
ERROR: No matching distribution found for sra-tools (from -r requirements.txt (line 6))


```

I get this error message when using both`pip` and `pip3`. 
Any idea what's causing this? I've already cloned the git repository to my home computer– are there any other dependencies I should be aware of?

**Comment by ESapenaVentura** [comment]
Hi @rachadele ! Thanks for contacting us

I have corrected that, if you could pull the latest commit from the master branch (`git pull origin master`) and confirm that it works, I will proceed to close the ticket

**Comment by rachadele** [comment]
yes, works now. thank you!
