### ISSUE TITLE
Update repository documentation

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/geo_to_hca#3]
**Description of the issue**:

I would like to update the documentation in this repository:

- [ ] Create a `Readme.md` under the `Apps` folder
- [x] Modify existing `Readme.md` at root:
  - [x] Move known issues to tickets of their own
  - [x] More detailed description of how to run the application (Prerequisites, installation, running)

**Comment by ESapenaVentura** [comment]
Work has been done on this so I'll review it and close if finished.

**Comment by ami-day** [comment]
@ESapenaVentura im not sure we need an additional Readme.md under the Apps folder?

**Comment by ami-day** [comment]
Done
