### ISSUE TITLE
Add parser to apps/geo_to_hca.py script

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/geo_to_hca#4]
**Description of the issue**:

Currently, the script `apps/geo_to_hca.py` takes predefined parameters as inputs and outputs. I would like to add a parser with default options to give the user the ability to:
- Choose a template [Default:`docs/hca_template.xlsx`]
   - (**Optional**): Choose a `header` row (e.g. in HCA metadata 4 is the header row with the programmatic names) [Default: `4`]
  - (**Optional**): Choose an `initial metadata input row` (e.g. in HCA metadata, 6 is the row number where you begin inputting the metadata on each sheet) [Default: `6`]
- Choose Output directory: Choose the output folder for the spreadsheets [Default: `spreadsheets/`]
- Choose file with accessions [No Default]
   - (**Optional**): Have another option to add space-separated accessions manually and merge them with the accessions obtained from

**Comment by ami-day** [comment]
@ESapenaVentura I'm not sure about this 3rd point:

"(Optional): Have another option to add space-separated accessions manually and merge them with the accessions obtained from"

I think it would be ideal to have the GEO accessions that are given as input stored in a text file and saved somewhere for our record; adding extra accessions at the command-line might result in loss of this information. We could name the input files in a way that links them back to the dataset backlog, with a particular time stamp for example. Ideally in the future, we might streamline the process of extracting accessions directly from a data backlog file. In that case, the file would have extra column names but as long as the accession name remains, this should not impact the working of the script.

**Comment by ESapenaVentura** [comment]
Given your last updates to the code, I thought we were moving towards having a report written after execution (In which case we would also need to add a `-o, --output_log` option), but happy to move in that direction, although I don't know how reliable an input text file is for keeping track of converted datasets

**Comment by ami-day** [comment]
I implemented this using @ESapenaVentura 's initial plan to include different input options (input file, string, comma separated list), as flexibility will be needed depending on speed at which a result is needed

**Comment by ami-day** [comment]
Closing the issue as this has been done and committed to my branch
